create sequence company_seq start 1 increment 1;
create sequence counter_seq start 1 increment 1;
create sequence house_seq start 1 increment 1;
create sequence region_seq start 1 increment 1;
create sequence tariff_seq start 1 increment 1;
create sequence user_seq start 1 increment 1;
create sequence value_seq start 1 increment 1;
create table companies (id int8 not null, inn int8, email varchar(255), name varchar(255), password varchar(255), role varchar(255), primary key (id));
create table counters (id int8 not null, date_checking timestamp, is_checking boolean not null, name varchar(255), type varchar(255), house_id int8, tariff_id int8, primary key (id));
create table counters_value (counter_id int8 not null, value_id int8 not null);
create table houses (id int8 not null, address varchar(255), email varchar(255), region_id int8, user_id int8, primary key (id));
create table houses_counter (house_id int8 not null, counter_id int8 not null);
create table houses_of_companies (house_id int8 not null, company_id int8 not null);
create table regions (id int8 not null, title varchar(255), house_id int8, primary key (id));
create table regions_tariff (region_id int8 not null, tariff_id int8 not null);
create table tariffs (id int8 not null, price numeric(19, 2), type varchar(255), tariff_id int8, primary key (id));
create table users (id int8 not null, email varchar(255), name varchar(255), password varchar(255), role varchar(255), primary key (id));
create table users_house (user_id int8 not null, house_id int8 not null);
create table values (id int8 not null, date timestamp, value numeric(19, 2), counter_id int8, primary key (id));
alter table if exists counters_value add constraint UK_2vhhhdlbj1t0lui64qhyvkhe3 unique (value_id);
alter table if exists houses_counter add constraint UK_4gh1ykd26ke3sq3keb2230c7 unique (counter_id);
alter table if exists regions_tariff add constraint UK_anyhqfq53x9puud1vgjkj2dw2 unique (tariff_id);
alter table if exists users_house add constraint UK_nf0327g0rkqtktbxm118dtwbo unique (house_id);
alter table if exists counters add constraint FKaa2mioyq622dfpx0sklt9qew0 foreign key (house_id) references houses;
alter table if exists counters add constraint FKbg1av4f89hlroid9d8eqysa6i foreign key (tariff_id) references tariffs;
alter table if exists counters_value add constraint FK71seq9tl1nfb8qkhbxi4hp1d9 foreign key (value_id) references values;
alter table if exists counters_value add constraint FKg8nvwd5smmu12is830vq70a5p foreign key (counter_id) references counters;
alter table if exists houses add constraint FKhycgy7nyyiaxatl5paqar6efk foreign key (region_id) references regions;
alter table if exists houses add constraint FK42al334evgs9vf8bnryjxa1vs foreign key (user_id) references users;
alter table if exists houses_counter add constraint FKn7uxywxjlre3vol68xi0qqnsh foreign key (counter_id) references counters;
alter table if exists houses_counter add constraint FK9ic0w6mnsgigk6eotd6y87kt7 foreign key (house_id) references houses;
alter table if exists houses_of_companies add constraint FKq4bae2yu9wqoptywsb4fghq6d foreign key (company_id) references companies;
alter table if exists houses_of_companies add constraint FKp8wkfrk1b0ukbllnrg4bsami7 foreign key (house_id) references houses;
alter table if exists regions add constraint FKbt4oma5kkb3jbrmltq20jh16g foreign key (house_id) references houses;
alter table if exists regions_tariff add constraint FK808omdilonqsi9c4vy76k123o foreign key (tariff_id) references tariffs;
alter table if exists regions_tariff add constraint FKihh1g5tq0pc9smsy5pyrdk274 foreign key (region_id) references regions;
alter table if exists tariffs add constraint FKqmnj7x4r2ph36spqq7ocaoe7r foreign key (tariff_id) references regions;
alter table if exists users_house add constraint FKd9pv4g4hin73cyenn8xrqx96b foreign key (house_id) references houses;
alter table if exists users_house add constraint FK8a52g91fv4ejylpyso107v33n foreign key (user_id) references users;
alter table if exists values add constraint FKjp9ifly9bomamb2h7ivop7ehs foreign key (counter_id) references counters;
