INSERT INTO tbl_regions (id, title) values (1, 'Республика Адыгея (Адыгея)');
INSERT INTO tbl_regions (id, title) values (2, 'Республика Башкортостан');
INSERT INTO tbl_regions (id, title) values (3, 'Республика Бурятия');
INSERT INTO tbl_regions (id, title) values (4, 'Республика Алтай');
INSERT INTO tbl_regions (id, title) values (5, 'Республика Дагестан');
INSERT INTO tbl_regions (id, title) values (6, 'Республика Ингушетия');
INSERT INTO tbl_regions (id, title) values (7, 'Кабардино-Балкарская Республика');
INSERT INTO tbl_regions (id, title) values (8, 'Республика Калмыкия');
INSERT INTO tbl_regions (id, title) values (9, 'Карачаево-Черкесская Республика');
INSERT INTO tbl_regions (id, title) values (10, 'Республика Карелия');
INSERT INTO tbl_regions (id, title) values (11, 'Республика Коми');
INSERT INTO tbl_regions (id, title) values (12, 'Республика Марий Эл');
INSERT INTO tbl_regions (id, title) values (13, 'Республика Мордовия');
INSERT INTO tbl_regions (id, title) values (14, 'Республика Саха (Якутия)');
INSERT INTO tbl_regions (id, title) values (15, 'Республика Северная Осетия - Алания');
INSERT INTO tbl_regions (id, title) values (16, 'Республика Татарстан (Татарстан)');
INSERT INTO tbl_regions (id, title) values (17, 'Республика Тыва');
INSERT INTO tbl_regions (id, title) values (18, 'Удмуртская Республика');
INSERT INTO tbl_regions (id, title) values (19, 'Республика Хакасия');
INSERT INTO tbl_regions (id, title) values (20, 'Чеченская Республика');
INSERT INTO tbl_regions (id, title) values (21, 'Чувашская Республика – Чувашия');
INSERT INTO tbl_regions (id, title) values (22, 'Алтайский край');
INSERT INTO tbl_regions (id, title) values (23, 'Краснодарский край');
INSERT INTO tbl_regions (id, title) values (24, 'Красноярский край');
INSERT INTO tbl_regions (id, title) values (25, 'Приморский край');
INSERT INTO tbl_regions (id, title) values (26, 'Ставропольский край');
INSERT INTO tbl_regions (id, title) values (27, 'Хабаровский край');
INSERT INTO tbl_regions (id, title) values (28, 'Амурская область');
INSERT INTO tbl_regions (id, title) values (29, 'Архангельская область');
INSERT INTO tbl_regions (id, title) values (30, 'Астраханская область');
INSERT INTO tbl_regions (id, title) values (31, 'Белгородская область');
INSERT INTO tbl_regions (id, title) values (32, 'Брянская область');
INSERT INTO tbl_regions (id, title) values (33, 'Владимирская область');
INSERT INTO tbl_regions (id, title) values (34, 'Волгоградская область');
INSERT INTO tbl_regions (id, title) values (35, 'Вологодская область');
INSERT INTO tbl_regions (id, title) values (36, 'Воронежская область');
INSERT INTO tbl_regions (id, title) values (37, 'Ивановская область');
INSERT INTO tbl_regions (id, title) values (38, 'Иркутская область');
INSERT INTO tbl_regions (id, title) values (39, 'Калининградская область');
INSERT INTO tbl_regions (id, title) values (40, 'Калужская область');
INSERT INTO tbl_regions (id, title) values (41, 'Камчатская область');
INSERT INTO tbl_regions (id, title) values (42, 'Кемеровская область');
INSERT INTO tbl_regions (id, title) values (43, 'Кировская область');
INSERT INTO tbl_regions (id, title) values (44, 'Костромская область');
INSERT INTO tbl_regions (id, title) values (45, 'Курганская область');
INSERT INTO tbl_regions (id, title) values (46, 'Курская область');
INSERT INTO tbl_regions (id, title) values (47, 'Ленинградская область');
INSERT INTO tbl_regions (id, title) values (48, 'Липецкая область');
INSERT INTO tbl_regions (id, title) values (49, 'Магаданская область');
INSERT INTO tbl_regions (id, title) values (50, 'Московская область');
INSERT INTO tbl_regions (id, title) values (51, 'Мурманская область');
INSERT INTO tbl_regions (id, title) values (52, 'Нижегородская область');
INSERT INTO tbl_regions (id, title) values (53, 'Новгородская область');
INSERT INTO tbl_regions (id, title) values (54, 'Новосибирская область');
INSERT INTO tbl_regions (id, title) values (55, 'Омская область');
INSERT INTO tbl_regions (id, title) values (56, 'Оренбургская область');
INSERT INTO tbl_regions (id, title) values (57, 'Орловская область');
INSERT INTO tbl_regions (id, title) values (58, 'Пензенская область');
INSERT INTO tbl_regions (id, title) values (59, 'Пермская область ');
INSERT INTO tbl_regions (id, title) values (60, 'Псковская область');
INSERT INTO tbl_regions (id, title) values (61, 'Ростовская область');
INSERT INTO tbl_regions (id, title) values (62, 'Рязанская область');
INSERT INTO tbl_regions (id, title) values (63, 'Самарская область');
INSERT INTO tbl_regions (id, title) values (64, 'Саратовская область');
INSERT INTO tbl_regions (id, title) values (65, 'Сахалинская область');
INSERT INTO tbl_regions (id, title) values (66, 'Свердловская область');
INSERT INTO tbl_regions (id, title) values (67, 'Смоленская область');
INSERT INTO tbl_regions (id, title) values (68, 'Тамбовская область');
INSERT INTO tbl_regions (id, title) values (69, 'Тверская область');
INSERT INTO tbl_regions (id, title) values (70, 'Томская область');
INSERT INTO tbl_regions (id, title) values (71, 'Тульская область');
INSERT INTO tbl_regions (id, title) values (72, 'Тюменская область');
INSERT INTO tbl_regions (id, title) values (73, 'Ульяновская область');
INSERT INTO tbl_regions (id, title) values (74, 'Челябинская область');
INSERT INTO tbl_regions (id, title) values (75, 'Читинская область');
INSERT INTO tbl_regions (id, title) values (76, 'Ярославская область');
INSERT INTO tbl_regions (id, title) values (77, 'Г. Москва');
INSERT INTO tbl_regions (id, title) values (78, 'Г. Санкт-Петербург');
INSERT INTO tbl_regions (id, title) values (79, 'Еврейская автономная область');
INSERT INTO tbl_regions (id, title) values (80, 'Агинский Бурятский автономный округ');
INSERT INTO tbl_regions (id, title) values (81, 'Коми-Пермяцкий автономный округ');
INSERT INTO tbl_regions (id, title) values (82, 'Корякский автономный округ');
INSERT INTO tbl_regions (id, title) values (83, 'Ненецкий автономный округ');
INSERT INTO tbl_regions (id, title) values (84, 'Таймырский (Долгано-Ненецкий) автономный округ');
INSERT INTO tbl_regions (id, title) values (85, 'Усть-Ордынский Бурятский автономный округ');
INSERT INTO tbl_regions (id, title) values (86, 'Ханты-Мансийский автономный округ - Югра');
INSERT INTO tbl_regions (id, title) values (87, 'Чукотский автономный округ');
INSERT INTO tbl_regions (id, title) values (88, 'Эвенкийский автономный округ');
INSERT INTO tbl_regions (id, title) values (89, 'Ямало-Ненецкий автономный округ');
SET SQL_SAFE_UPDATES=0;
UPDATE region_seq SET next_val=90 where next_val=1;
SET SQL_SAFE_UPDATES=1;