server:
  port: ${PORT:8090}
  hostname: localhost
spring:
  application:
    name: manager-counters
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
     name: 'dataManager'
     url: jdbc:${DATABASE_PATH:mysql://localhost:3306/db_mancounters?serverTimezone=UTC}
     username: ${DATABASE_USER:root}
     password: ${DATABASE_PASSWORD:Nbirf}

#    driver-class-name: org.postgresql.Driver
#    url: jdbc:${DATABASE_PATH:postgresql://localhost:5432/db_ManCounters}
#    username: ${DATABASE_USER:postgres}
#    password: ${DATABASE_PASSWORD:123456}
#    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings
logging:
  level:
    org.springframework.web: DEBUG
#    org.springframework.ws: DEBUG








